### ISSUE TITLE
How to obtain the id of domain models？

### ISSUE THREAD

**Issue by yuan102379** [mtassia/TIAMMAt#1]
Hi @mtassia ，

TIAMMAt looks likely a nice program for the identification of Pfam domains of non-model species.

Now, I have tried this program several times for the domain revision of numerous teleosts, and it works well based on the hmmsearch and Pfam database.

Additionally, the ids of specific functional domains also need, which are download and converted to the standard format using the Grab_model.sh.  

However, It seems to be much tedious to search the domain id every time. 

Could you provide a list including the information of all the domains in Pfam database? It would help users to find the specific domain models accurately, and avoid some unnecessary mistakes.

Yours,

Yuan

**Comment by mtassia** [comment]
Thanks for the feedback, @yuan102379!

I will investigate options to expedite searching for domain IDs; however, to get comprehensive information on the domains themselves, there likely will be no better substitute than the Pfam website (http://pfam.xfam.org/).
